### ISSUE TITLE
Universal Kiosk will not go to any link

### ISSUE THREAD

**Issue by lwallin** [hermanbergwerf/universal-kiosk#1]
Recently loaded Universal Kiosk on a class set of chromebooks. The app is loaded, the wifi security is shut off, and the Universal Kiosk opens up, HOWEVER it will not go to ANY link at all (even google.com). "Error Address Unreachable" shows up. I'm trying to give my final exam on chromebooks as a Google Form, it would be extremely helpful to hear back from you asap with any advice.

**Comment by hermanbergwerf** [comment]
My apologies for my late response (I was somehow not notified of this issue). In theory the kiosk is exactly the same as the chrome web browser which means you can access any address. The catch is that you have to include the request protocol (http:// or https://) I will add a automatic protocol resolver (that adds http:// if there is no protocol specified) to resolve this issue in the future.
